services:
  # 1. База данных PostgreSQL
  db:
    image: postgres:18.1
    container_name: postgres
    restart: always
    environment:
      # Переопределение переменных для образа Postgres
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /home/deploy/pg_data:/var/lib/postgresql/18/docker
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Redis
  redis:
    image: redis:8.4
    container_name: redis
    restart: always
    volumes:
      - /home/deploy/redis_data:/data
    command: redis-server --port ${REDIS_PORT} --loglevel warning --requirepass ${REDIS_PASSWORD} --databases ${REDIS_DB_COUNT}
    networks:
      - app_network

  # 3. Backend (FastAPI)
  fastapi:
    image: ${IMAGE_NAME_FASTAPI}
    container_name: fastapi
    restart: always
    volumes:
      - /home/deploy/media:/Vellory/media
      - /home/deploy/logs:/Vellory/logs
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --forwarded-allow-ips="*"
    environment:
      ENVIRONMENT: production #app/api/routers/system.py
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # 4. Nginx (Reverse Proxy)
  nginx:
    image: ${IMAGE_NAME_NGINX}
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/deploy/media:/Vellory/media
      - /etc/letsencrypt/live/braxor.ru:/etc/letsencrypt/live/braxor.ru:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
    networks:
      - app_network
    depends_on:
      - fastapi


# Тома для постоянного хранения данных
# volumes:
#  postgres_data:
#  redis_data:
#  vellory_media:
#  vellory_logs:

# Сеть для общения контейнеров
networks:
  app_network:
    driver: bridge