services:
  # 1. База данных PostgreSQL
  db:
    image: postgres:18.1
    container_name: postgres_db
    restart: always
    environment:
      # Переопределение переменных для образа Postgres
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /home/super/pg_data:/var/lib/postgresql/18/docker
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Redis
  redis:
    image: redis:8.4
    container_name: redis_cache
    restart: always
    command: redis-server --port ${REDIS_PORT} --loglevel warning --requirepass ${REDIS_PASSWORD} --databases ${REDIS_DB_COUNT}
    networks:
      - app_network

  # 3. Backend (FastAPI)
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    volumes:
      - /home/super/vellory/media/avatars:/Vellory/media/avatars
      - /home/super/vellory/frontend/static:/Vellory/frontend/static
      - /home/super/vellory/media:/Vellory/media
      - /home/super/vellory/media/img:/Vellory/media/img
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --forwarded-allow-ips="*"
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # 4. Nginx (Reverse Proxy)
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/super/vellory/media:/Vellory/media:ro
      - /home/super/vellory/frontend:/Vellory/frontend:ro
      - /etc/letsencrypt/live/braxor.ru:/etc/letsencrypt/live/braxor.ru:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
    networks:
      - app_network
    depends_on:
      - fastapi


# Тома для постоянного хранения данных
volumes:
  postgres_data:
  redis_data:

# Сеть для общения контейнеров
networks:
  app_network:
    driver: bridge