name: deploy to server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Авторизация
      - name: Log in to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      #Настройка Buildx (нужен для кэша gha)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2. Сборка и пуш FASTAPI
      - name: Build and push FastAPI
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.GITLAB_REGISTRY_IMAGE }}/fastapi:latest
            ${{ secrets.GITLAB_REGISTRY_IMAGE }}/fastapi:${{ github.sha }}

          # Эти строки включают облачный кэш внутри GitHub
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 2. Сборка и пуш nginx
      - name: Build and push nginx
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.GITLAB_REGISTRY_IMAGE }}/nginx:latest
            ${{ secrets.GITLAB_REGISTRY_IMAGE }}/nginx:${{ github.sha }}

          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 3. Копируем ТОЛЬКО compose.yaml на сервер
      - name: Copy docker-compose to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: ./compose.yaml #Обязательно использовать явный путь
          target: "/home/deploy/" # Папка пользователя

      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Переходим в папку пользователя
            cd /home/deploy/
            
            # Авторизация в GitLab
            echo "${{ secrets.GITLAB_PASSWORD }}" | docker login registry.gitlab.com -u "${{ secrets.GITLAB_USERNAME }}" --password-stdin

            # Создаем переменные для текущей сессии и запускаем команды
            export IMAGE_NAME_FASTAPI="${{ secrets.GITLAB_REGISTRY_IMAGE }}/fastapi:latest"
            export IMAGE_NAME_NGINX="${{ secrets.GITLAB_REGISTRY_IMAGE }}/nginx:latest"

            # Загружает последние версии Docker-образов сервисов fastapi и nginx
            docker-compose pull fastapi nginx
            # Перезапускаем контейнеры
            docker-compose up -d fastapi nginx

            #Очистка старых ненужных образов (экономим место)
            docker image prune -f


