name: deploy to server
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect and run script
        uses: appleboy/ssh-action@v1.2.4 #Устанавливаем последнюю версию
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "--- Проверка связи с сервером ---"
            whoami
            hostname
            uptime
            echo "--- Список файлов в текущей директории ---"
            ls -la
            echo "--- Проверка завершена успешно ----"